/*This table specifies cities name and country, depends on citycode. (WAW airport is located in Warsaw, Poland)*/
CREATE TABLE CITY 
	(CITYCODE VARCHAR(4),
	CITY VARCHAR(20),
	COUNTRY VARCHAR(20),
	PRIMARY KEY (CITYCODE));

/*This table specifies staff  surname, name, date of birth*/
CREATE TABLE STAFF 
	(EMPNUM INT, 
	SURNAME VARCHAR(20),
	NAME VARCHAR(20),
	DATEOFBIRTH DATE,
	PRIMARY KEY (EMPNUM));

/*This table specifies staff phone and allows staff to have multiple phones*/
CREATE TABLE STAFFPHONE
	(EMPNUM INT,
	PHONENUMBER VARCHAR(20),
	PRIMARY KEY (EMPNUM, PHONENUMBER),
	FOREIGN KEY (EMPNUM) REFERENCES STAFF);

/*This table specifies staff address and allows staff to have multiple addresses*/
CREATE TABLE STAFFADDRESS 
	(EMPNUM INT,
	ADDRESS VARCHAR(200),
	PRIMARY KEY (EMPNUM, ADDRESS),
	FOREIGN KEY (EMPNUM) REFERENCES STAFF);

/*This table specifies aircraft manufacture and model number*/
CREATE TABLE AIRCRAFT
	(AIRCRAFT VARCHAR(20),
	MANUFACTURE VARCHAR(20),
	MODELNUMBER INT,
	PRIMARY KEY (AIRCRAFT));

/*This table connects aircraft and pilot type rating, type rating is certification that allows
the pilot to operate specific type of aircraft*/
CREATE TABLE PLANESCANFLY
	(TYPERATING INT, 
	AIRCRAFT VARCHAR(20) UNIQUE,
	PRIMARY KEY (TYPERATING),
	FOREIGN KEY (AIRCRAFT) REFERENCES AIRCRAFT);

/*This table specifies total flight hours of the pilot*/
CREATE TABLE PILOT
	(EMPNUM INT,
	TOTALFLIGHTHOURS FLOAT, 
	PRIMARY KEY (EMPNUM),
	FOREIGN KEY (EMPNUM) REFERENCES STAFF,)

/*This table is a bridge between Pilot and PlanesCanFly tables*/
CREATE TABLE LICENSE
	(EMPNUM INT,
	TYPERATING INT,
	PRIMARY KEY (EMPNUM, TYPERATING),
	FOREIGN KEY (TYPERATING) REFERENCES PLANESCANFLY,
	FOREIGN KEY (EMPNUM) REFERENCES PILOT);

/*This table specifies aircraft of the airplane*/
CREATE TABLE AIRPLANE 
	(NUMSER INT,
	AIRCRAFT VARCHAR(20),
	PRIMARY KEY (NUMSER),
	FOREIGN KEY (AIRCRAFT) REFERENCES AIRCRAFT);

/*This table specifies origin, destination, arrival time, departure time, airplane, pilot and gate of the flight */
CREATE TABLE FLIGHT
	(FLIGHTNUM VARCHAR(20),
	ORIGIN VARCHAR(4) NOT NULL,
	DESTINATION VARCHAR(4) NOT NULL,
	DEPTIME DATETIME,
	ARRTIME DATETIME,
	AIRPLANE INT NOT NULL,
	PILOT INT NOT NULL,
	GATE VARCHAR(4),
	SHEDULEID INT,
	PRIMARY KEY (FLIGHTNUM),
	FOREIGN KEY (ORIGIN) REFERENCES CITY,
	FOREIGN KEY (DESTINATION) REFERENCES CITY,
	FOREIGN KEY (AIRPLANE) REFERENCES AIRPLANE,
	FOREIGN KEY (PILOT) REFERENCES PILOT);

/*This is the bridge table between Staff and Flight tables*/
CREATE TABLE CREW
	(FLIGHTNUM VARCHAR(20), 
	EMPNUM INT, 
	PRIMARY KEY (FLIGHTNUM, EMPNUM),
	FOREIGN KEY (FLIGHTNUM) REFERENCES FLIGHT,
	FOREIGN KEY (EMPNUM) REFERENCES STAFF);

/*This table allows multiple intermediate city*/
CREATE TABLE INTERMEDIATECITY
	(FLIGHTNUM VARCHAR(20),
	CITY VARCHAR(4),
	ARRTIME DATETIME,
	DEPTIME DATETIME,
	PRIMARY KEY (FLIGHTNUM, CITY),
	FOREIGN KEY (CITY) REFERENCES CITY,
	FOREIGN KEY (FLIGHTNUM) REFERENCES FLIGHT);

/*This table specifies schedule type for certain origin, destination, arrival time, departure time*/
CREATE TABLE SCHEDULE
	(SCHEDULEID INT,
	SCHEDULETYPE VARCHAR(20),
	ORIGIN VARCHAR(4) NOT NULL,
	DESTINATION VARCHAR(4) NOT NULL,
	DEPTIME DATETIME,
	ARRTIME DATETIME,
	PRIMARY KEY (SCHEDULEID),
	FOREIGN KEY (ORIGIN) REFERENCES CITY,
	FOREIGN KEY (DESTINATION) REFERENCES CITY);

/*This table specifies surname and name of the passenger*/
CREATE TABLE PASSENGER
	( PASSPORT VARCHAR(20),
	SURNAME VARCHAR(20),
	NAME VARCHAR(20),
	PRIMARY KEY (PASSPORT));

/*This table specifies passport, flight number, seat number and class of the booking*/
CREATE TABLE BOOKING
	(BOOKINGID INT,
	PASSPORT VARCHAR(20) NOT NULL,
	FLIGHTNUM VARCHAR(20) NOT NULL,
	SEAT VARCHAR(20),
	CLASS VARCHAR(20),
	PRIMARY KEY (BOOKINGID),
	FOREIGN KEY (PASSPORT) REFERENCES PASSENGER,
	FOREIGN KEY (FLIGHTNUM) REFERENCES FLIGHT);

/*This table specifies passenger phone and allows passenger to have multiple phones*/
CREATE TABLE PASSENGERPHONE 
	(PASSPORT VARCHAR(20),
	PHONENUMBER VARCHAR(20),
	PRIMARY KEY (PASSPORT, PHONENUMBER),
	FOREIGN KEY (PASSPORT) REFERENCES PASSENGER);

/*This table specifies passenger address and allows passenger to have multiple addresses*/
CREATE TABLE PASSENGERADDRESS 
	(PASSPORT VARCHAR(20),
	ADDRESS VARCHAR(200),
	PRIMARY KEY (PASSPORT, ADDRESS),
	FOREIGN KEY (PASSPORT) REFERENCES PASSENGER);






